name: Check numbertotext
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install coverage pylint
      - name: Pylint
        run: pylint numbertotext/numbertotext.py
      - name: Run tests and collect coverage
        run: coverage run -m unittest tests/tests.py
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3